from setuptools import Command

class bdist_wheel(Command):
    plat_name: str | None
    root_is_pure: bool
    def finalize_options(self) -> None: ...
    def run(self) -> None: ...
    def get_tag(self) -> tuple[str, str, str]: ...
